version: '3.8'
services:
  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - app_network

  clickhouse:
    image: clickhouse/clickhouse-server:23.8
    ports:
      - "8123:8123"
      - "9000:9000"
    networks:
      - app_network

  app:
    build: .
    ports:
      - "8000:8000"
    depends_on:
      - rabbitmq
      - clickhouse
    volumes:
      - ./app:/app
    environment:
      RABBITMQ_HOST: rabbitmq
      CLICKHOUSE_HOST: clickhouse
    networks:
      - app_network
networks:
  app_network:
    driver: bridge
